pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: inbound-agent
            image: jenkins/inbound-agent
            volumeMounts:
            - mountPath: /var/run/docker.sock
              name: dockersock
          volumes:
          - name: dockersock
            hostPath:
                path: /var/run/docker.sock

            command:
            - cat
            tty: true
        '''
    }
  }
  parameters {
        string(
           name: "Branch_Name",
           defaultValue: 'master',
           description: '')
           string(
              name: "Image_Name",
              defaultValue: 'py',
              description: '')
           string(
              name: "Image_Tag",
              defaultValue: 'latest',
              description: 'Image tag')
          booleanParam(
             name: "PushImage",
             defaultValue: false)
      }
  stages {
    stage('build image') {
      steps {
            script {
              echo "Bulding docker images"
              sh 'docker ps'
            }
        }
      }
    }
}
