pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: python
            image: python:2-alpine
            command:
            - cat
            tty: true
        '''
    }
  }
  stages {
    stage('check python') {
      steps {
        container('python') {
          sh 'python --version'
          sh 'pwd'
          sh 'ls'
        }
      }
    }
  }
}