pipeline {
  agent {
    kubernetes {
      yaml '''
        apiVersion: v1
        kind: Pod
        spec:
          containers:
          - name: python
            image: python:2-alpine
            command:
            - cat
            tty: true
        '''
    }
  }
  parameters {
        string(
           name: "Branch_Name",
           defaultValue: 'master',
           description: '')
           string(
              name: "Image_Name",
              defaultValue: 'py',
              description: '')
           string(
              name: "Image_Tag",
              defaultValue: 'latest',
              description: 'Image tag')
          booleanParam(
             name: "PushImage",
             defaultValue: false)
      }
  stages {
    stage('build image') {
      steps {
            script {
               echo "Bulding docker images"
               def buildArgs = """\
                -f Dockerfile \
                ."""
                docker.build(
                   "${params.Image_Name}:${params.Image_Tag}",
                   buildArgs)
            }
        }
      }
    }
  }
}